export const  FETCH_QUIZ_START= "FETCH_QUIZ_START"
export const  FETCH_QUIZ_FINISH= "FETCH_QUIZ_FINISH"
export const  FETCH_QUIZ_ERROR= "FETCH_QUIZ_ERROR"
export const  FETCH_QUIZ_TEST_ID_FINISH= "FETCH_QUIZ_TEST_ID_FINISH"

export const QUIZ_TEST_SET_STATE = 'QUIZ_TEST_SET_STATE'
export const QUIZ_TEST_SET_STATE_FINISH = 'QUIZ_TEST_SET_STATE_FINISH'
export const QUIZ_TEST_SET_STATE_NEXT_QUESTION = 'QUIZ_TEST_SET_STATE_NEXT_QUESTION'
export const QUIZ_TEST_SET_STATE_DEFAULT = 'QUIZ_TEST_SET_STATE_DEFAULT'

export const QUIZ_CREATOR_QUESTION = 'QUIZ_CREATOR_QUESTION'
export const QUIZ_CREATOR_RESET = 'QUIZ_CREATOR_RESET'