export const  FETCH_QUIZ_START= "FETCH_QUIZ_START"
export const  FETCH_QUIZ_FINISH= "FETCH_QUIZ_FINISH"
export const  FETCH_QUIZ_ERROR= "FETCH_QUIZ_ERROR"
export const  FETCH_QUIZ_TEST_ID_FINISH= "FETCH_QUIZ_TEST_ID_FINISH"